-- ============================================
-- Workflow Engine Database Schema for Oracle
-- ============================================

-- Table: Workflow Definitions
CREATE TABLE WF_DEFINITIONS (
    ID VARCHAR2(100) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    VERSION VARCHAR2(50) NOT NULL,
    STEPS_JSON CLOB NOT NULL,
    INITIAL_STEP_ID VARCHAR2(100) NOT NULL,
    VARIABLES_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT UK_WF_DEF_NAME_VERSION UNIQUE (NAME, VERSION)
);

-- Table: Workflow Instances
CREATE TABLE WF_INSTANCES (
    ID VARCHAR2(100) PRIMARY KEY,
    WORKFLOW_DEFINITION_ID VARCHAR2(100) NOT NULL,
    CURRENT_STEP_ID VARCHAR2(100),
    STATUS NUMBER(1) NOT NULL,  -- 0=Created, 1=Running, 2=Waiting, 3=Completed, 4=Failed, 5=Cancelled, 6=Suspended
    VARIABLES_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY VARCHAR2(255),
    CORRELATION_ID VARCHAR2(255),
    CONSTRAINT FK_WF_INST_DEF FOREIGN KEY (WORKFLOW_DEFINITION_ID) 
        REFERENCES WF_DEFINITIONS(ID) ON DELETE CASCADE
);

-- Table: Step Instances
CREATE TABLE WF_STEP_INSTANCES (
    ID VARCHAR2(100) PRIMARY KEY,
    WORKFLOW_INSTANCE_ID VARCHAR2(100) NOT NULL,
    STEP_DEFINITION_ID VARCHAR2(100) NOT NULL,
    STEP_NAME VARCHAR2(255) NOT NULL,
    STEP_TYPE VARCHAR2(50) NOT NULL,
    STATUS NUMBER(1) NOT NULL,  -- 0=Pending, 1=Running, 2=WaitingForInput, 3=Scheduled, 4=Completed, 5=Failed, 6=Skipped, 7=Timeout
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    ASSIGNED_TO VARCHAR2(255),
    INPUT_DATA_JSON CLOB,
    OUTPUT_DATA_JSON CLOB,
    ERROR_MESSAGE CLOB,
    TRANSITION_TAKEN VARCHAR2(100),
    RETRY_COUNT NUMBER(3) DEFAULT 0,
    CONSTRAINT FK_WF_STEP_INST FOREIGN KEY (WORKFLOW_INSTANCE_ID) 
        REFERENCES WF_INSTANCES(ID) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX IDX_WF_INST_DEF_ID ON WF_INSTANCES(WORKFLOW_DEFINITION_ID);
CREATE INDEX IDX_WF_INST_STATUS ON WF_INSTANCES(STATUS);
CREATE INDEX IDX_WF_INST_CORRELATION ON WF_INSTANCES(CORRELATION_ID);
CREATE INDEX IDX_WF_STEP_INST_ID ON WF_STEP_INSTANCES(WORKFLOW_INSTANCE_ID);
CREATE INDEX IDX_WF_STEP_STATUS ON WF_STEP_INSTANCES(STATUS);
CREATE INDEX IDX_WF_STEP_ASSIGNED ON WF_STEP_INSTANCES(ASSIGNED_TO);
CREATE INDEX IDX_WF_STEP_SCHEDULED ON WF_STEP_INSTANCES(STATUS, STARTED_AT);

-- Comments for documentation
COMMENT ON TABLE WF_DEFINITIONS IS 'Stores workflow process definitions';
COMMENT ON TABLE WF_INSTANCES IS 'Stores runtime workflow instances';
COMMENT ON TABLE WF_STEP_INSTANCES IS 'Stores individual step executions within workflow instances';

-- ============================================
-- Optional: Audit History Table
-- ============================================
CREATE TABLE WF_STEP_HISTORY (
    ID VARCHAR2(100) PRIMARY KEY,
    WORKFLOW_INSTANCE_ID VARCHAR2(100) NOT NULL,
    STEP_INSTANCE_ID VARCHAR2(100) NOT NULL,
    ACTION VARCHAR2(50) NOT NULL,  -- STARTED, COMPLETED, FAILED, etc.
    TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    USER_ID VARCHAR2(255),
    DETAILS CLOB,
    CONSTRAINT FK_WF_HIST_INST FOREIGN KEY (WORKFLOW_INSTANCE_ID) 
        REFERENCES WF_INSTANCES(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_WF_HIST_INST_ID ON WF_STEP_HISTORY(WORKFLOW_INSTANCE_ID);
CREATE INDEX IDX_WF_HIST_STEP_ID ON WF_STEP_HISTORY(STEP_INSTANCE_ID);
CREATE INDEX IDX_WF_HIST_TIMESTAMP ON WF_STEP_HISTORY(TIMESTAMP);

COMMENT ON TABLE WF_STEP_HISTORY IS 'Audit log for workflow step executions';

-- ============================================
-- Sample Cleanup Procedures
-- ============================================

-- Procedure to cleanup completed workflows older than specified days
CREATE OR REPLACE PROCEDURE CLEANUP_OLD_WORKFLOWS(p_days_old NUMBER DEFAULT 90)
IS
BEGIN
    DELETE FROM WF_INSTANCES
    WHERE STATUS IN (3, 4, 5)  -- Completed, Failed, Cancelled
      AND COMPLETED_AT < SYSTIMESTAMP - INTERVAL p_days_old DAY;
    
    COMMIT;
END;
/

-- Grant necessary permissions (adjust schema name as needed)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON WF_DEFINITIONS TO your_app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON WF_INSTANCES TO your_app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON WF_STEP_INSTANCES TO your_app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON WF_STEP_HISTORY TO your_app_user;
-- GRANT EXECUTE ON CLEANUP_OLD_WORKFLOWS TO your_app_user;
